window.__ENV__ = {
  VITE_SUPABASE_URL: 'https://lzosvvbzvopamkjcuzpy.supabase.co',
  VITE_SUPABASE_ANON_KEY: 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imx6b3N2dmJ6dm9wYW1ramN1enB5Iiwicm9sZSI6ImFub24iLC',
  VITE_API_BASE_URL: 'https://somiti-auth-backend.netlify.app/.netlify/functions/auth'
};
console.log('[env] env.js generated by CI');
