import jsPDF from 'jspdf'

export const openReceiptPdf = async (transaction) => {
  console.log('pdfReceipt: open start', transaction)
  const doc = new jsPDF({ orientation: 'portrait', unit: 'mm', format: 'a5' })
  const pxToMm = (px) => (px * 25.4) / 96
  const loadFontAsBase64 = async (url) => {
    const res = await fetch(url)
    const buf = await res.arrayBuffer()
    const bytes = new Uint8Array(buf)
    let binary = ''
    for (let i = 0; i < bytes.length; i++) binary += String.fromCharCode(bytes[i])
    return btoa(binary)
  }
  const ensureBengaliFont = async () => {
    try {
      console.log('pdfReceipt: font load')
      const base64 = await loadFontAsBase64('/fonts/NotoSansBengali-Regular.ttf')
      doc.addFileToVFS('NotoSansBengali-Regular.ttf', base64)
      doc.addFont('NotoSansBengali-Regular.ttf', 'NotoSansBengali', 'normal')
      doc.setFont('NotoSansBengali', 'normal')
    } catch (e) {
      console.log('pdfReceipt: font load failed', e)
      doc.setFont('helvetica', 'normal')
    }
  }
  const renderBanglaTextImage = async (text, fontSizePx = 12) => {
    try {
      const fontFace = new FontFace('NotoSansBengaliInline', 'url(/fonts/NotoSansBengali-Regular.ttf)')
      await fontFace.load()
      document.fonts.add(fontFace)
      await document.fonts.ready
      const scale = 4
      const tmp = document.createElement('canvas').getContext('2d')
      tmp.font = `${fontSizePx}px "NotoSansBengaliInline", "Noto Sans Bengali", sans-serif`
      const m = tmp.measureText(text)
      const ascent = Math.ceil(m.actualBoundingBoxAscent || fontSizePx * 0.8)
      const descent = Math.ceil(m.actualBoundingBoxDescent || fontSizePx * 0.2)
      const w = Math.ceil(m.width) + 8
      const h = ascent + descent + 6
      const canvas = document.createElement('canvas')
      canvas.width = w * scale
      canvas.height = h * scale
      const ctx = canvas.getContext('2d')
      ctx.imageSmoothingEnabled = true
      ctx.imageSmoothingQuality = 'high'
      ctx.setTransform(scale, 0, 0, scale, 0, 0)
      ctx.fillStyle = '#000'
      ctx.font = `${fontSizePx}px "NotoSansBengaliInline", "Noto Sans Bengali", sans-serif`
      ctx.textBaseline = 'alphabetic'
      ctx.fillText(text, 0, ascent)
      const dataUrl = canvas.toDataURL('image/png')
      return { dataUrl, wMm: pxToMm(w), hMm: pxToMm(h) }
    } catch (e) {
      console.log('pdfReceipt: renderBanglaTextImage failed', e)
      return null
    }
  }
  const getGeneratedAtText = () => {
    const d = new Date()
    const yyyy = d.getFullYear()
    const mm = String(d.getMonth() + 1).padStart(2, '0')
    const dd = String(d.getDate()).padStart(2, '0')
    let hours = d.getHours()
    const ampm = hours >= 12 ? 'PM' : 'AM'
    hours = hours % 12
    if (hours === 0) hours = 12
    const hh = String(hours).padStart(2, '0')
    const min = String(d.getMinutes()).padStart(2, '0')
    const s = `Generated by fulmurigram.site on ${yyyy}-${mm}-${dd} at ${hh}:${min} ${ampm}`
    console.log('pdfReceipt: footer text', s)
    return s
  }
  const drawHeader = async () => {
    const pageWidth = doc.internal.pageSize.getWidth()
    const titleImg = await renderBanglaTextImage('লেনদেন রসিদ', 14)
    if (titleImg) {
      const x = (pageWidth / 2) - (titleImg.wMm / 2)
      doc.addImage(titleImg.dataUrl, 'PNG', x, 18, titleImg.wMm, titleImg.hMm)
    }
  }
  const drawBody = async () => {
    doc.setDrawColor(220)
    doc.setFontSize(9)
    const pageWidth = doc.internal.pageSize.getWidth()
    const contentWidth = Math.min(120, pageWidth - 20)
    const contentX = (pageWidth - contentWidth) / 2
    const startY = 28
    const rows = [
      ['সদস্য', transaction.memberName || 'অজানা সদস্য'],
      ['ধরন', (transaction.type || transaction.transactionType || 'other')],
      ['পরিমাণ', `৳ ${(transaction.amount || 0).toLocaleString('bn-BD')}`],
      ['পেমেন্ট পদ্ধতি', (transaction.paymentMethod || 'cash')],
      ['তারিখ/সময়', `${transaction.date ? (new Date(transaction.date)).toLocaleDateString('bn-BD', { year:'numeric', month:'long', day:'numeric' }) : ''}${transaction.time ? ` • ${transaction.time}` : ''}`],
      ['রেফারেন্স', transaction.reference || ''],
      ['প্রক্রিয়াকারী', transaction.processedBy || 'ক্যাশিয়ার']
    ]
    let y = startY
    for (const [label, value] of rows) {
      const labelImg = await renderBanglaTextImage(String(label), 10)
      if (labelImg) doc.addImage(labelImg.dataUrl, 'PNG', contentX + 4, y, labelImg.wMm, labelImg.hMm)
      const valImg = await renderBanglaTextImage(String(value), 11)
      if (valImg) doc.addImage(valImg.dataUrl, 'PNG', contentX + 38, y, valImg.wMm, valImg.hMm)
      const lineHeight = Math.max(8, (valImg?.hMm || 8) + 2)
      y += lineHeight
    }
    const totalHeight = y - startY
    doc.roundedRect(contentX, startY - 4, contentWidth, totalHeight + 8, 2, 2)
  }
  const drawFooter = () => {
    const pageWidth = doc.internal.pageSize.getWidth()
    const footerText = getGeneratedAtText()
    doc.setFont('helvetica', 'bold')
    doc.setTextColor(37, 99, 235)
    doc.setFontSize(10)
    doc.text(footerText, pageWidth / 2, 138, { align: 'center' })
  }
  await ensureBengaliFont()
  await drawHeader()
  await drawBody()
  drawFooter()
  const blob = doc.output('blob')
  const url = URL.createObjectURL(blob)
  window.open(url, '_blank')
  console.log('pdfReceipt: open done')
}

export const downloadReceiptPdf = async (transaction) => {
  console.log('pdfReceipt: download start', transaction)
  const doc = new jsPDF({ orientation: 'portrait', unit: 'mm', format: 'a5' })
  const pxToMm = (px) => (px * 25.4) / 96
  const loadFontAsBase64 = async (url) => {
    const res = await fetch(url)
    const buf = await res.arrayBuffer()
    const bytes = new Uint8Array(buf)
    let binary = ''
    for (let i = 0; i < bytes.length; i++) binary += String.fromCharCode(bytes[i])
    return btoa(binary)
  }
  const ensureBengaliFont = async () => {
    try {
      console.log('pdfReceipt: font load')
      const base64 = await loadFontAsBase64('/fonts/NotoSansBengali-Regular.ttf')
      doc.addFileToVFS('NotoSansBengali-Regular.ttf', base64)
      doc.addFont('NotoSansBengali-Regular.ttf', 'NotoSansBengali', 'normal')
      doc.setFont('NotoSansBengali', 'normal')
    } catch (e) {
      console.log('pdfReceipt: font load failed', e)
      doc.setFont('helvetica', 'normal')
    }
  }
  const renderBanglaTextImage = async (text, fontSizePx = 12) => {
    try {
      const fontFace = new FontFace('NotoSansBengaliInline', 'url(/fonts/NotoSansBengali-Regular.ttf)')
      await fontFace.load()
      document.fonts.add(fontFace)
      await document.fonts.ready
      const scale = 4
      const tmp = document.createElement('canvas').getContext('2d')
      tmp.font = `${fontSizePx}px "NotoSansBengaliInline", "Noto Sans Bengali", sans-serif`
      const m = tmp.measureText(text)
      const ascent = Math.ceil(m.actualBoundingBoxAscent || fontSizePx * 0.8)
      const descent = Math.ceil(m.actualBoundingBoxDescent || fontSizePx * 0.2)
      const w = Math.ceil(m.width) + 8
      const h = ascent + descent + 6
      const canvas = document.createElement('canvas')
      canvas.width = w * scale
      canvas.height = h * scale
      const ctx = canvas.getContext('2d')
      ctx.imageSmoothingEnabled = true
      ctx.imageSmoothingQuality = 'high'
      ctx.setTransform(scale, 0, 0, scale, 0, 0)
      ctx.fillStyle = '#000'
      ctx.font = `${fontSizePx}px "NotoSansBengaliInline", "Noto Sans Bengali", sans-serif`
      ctx.textBaseline = 'alphabetic'
      ctx.fillText(text, 0, ascent)
      const dataUrl = canvas.toDataURL('image/png')
      return { dataUrl, wMm: pxToMm(w), hMm: pxToMm(h) }
    } catch (e) {
      console.log('pdfReceipt: renderBanglaTextImage failed', e)
      return null
    }
  }
  const getGeneratedAtText = () => {
    const d = new Date()
    const yyyy = d.getFullYear()
    const mm = String(d.getMonth() + 1).padStart(2, '0')
    const dd = String(d.getDate()).padStart(2, '0')
    let hours = d.getHours()
    const ampm = hours >= 12 ? 'PM' : 'AM'
    hours = hours % 12
    if (hours === 0) hours = 12
    const hh = String(hours).padStart(2, '0')
    const min = String(d.getMinutes()).padStart(2, '0')
    const s = `Generated by fulmurigram.site on ${yyyy}-${mm}-${dd} at ${hh}:${min} ${ampm}`
    console.log('pdfReceipt: footer text', s)
    return s
  }
  const drawHeader = async () => {
    const pageWidth = doc.internal.pageSize.getWidth()
    const titleImg = await renderBanglaTextImage('লেনদেন রসিদ', 14)
    if (titleImg) {
      const x = (pageWidth / 2) - (titleImg.wMm / 2)
      doc.addImage(titleImg.dataUrl, 'PNG', x, 18, titleImg.wMm, titleImg.hMm)
    }
  }
  const drawBody = async () => {
    doc.setDrawColor(220)
    doc.setFontSize(9)
    const pageWidth = doc.internal.pageSize.getWidth()
    const contentWidth = Math.min(120, pageWidth - 20)
    const contentX = (pageWidth - contentWidth) / 2
    const startY = 28
    const rows = [
      ['সদস্য', transaction.memberName || 'অজানা সদস্য'],
      ['ধরন', (transaction.type || transaction.transactionType || 'other')],
      ['পরিমাণ', `৳ ${(transaction.amount || 0).toLocaleString('bn-BD')}`],
      ['পেমেন্ট পদ্ধতি', (transaction.paymentMethod || 'cash')],
      ['তারিখ/সময়', `${transaction.date ? (new Date(transaction.date)).toLocaleDateString('bn-BD', { year:'numeric', month:'long', day:'numeric' }) : ''}${transaction.time ? ` • ${transaction.time}` : ''}`],
      ['রেফারেন্স', transaction.reference || ''],
      ['প্রক্রিয়াকারী', transaction.processedBy || 'ক্যাশিয়ার']
    ]
    let y = startY
    for (const [label, value] of rows) {
      doc.setTextColor(100)
      const labelImg = await renderBanglaTextImage(String(label), 10)
      if (labelImg) doc.addImage(labelImg.dataUrl, 'PNG', contentX + 4, y, labelImg.wMm, labelImg.hMm)
      doc.setTextColor(30)
      const valImg = await renderBanglaTextImage(String(value), 11)
      if (valImg) doc.addImage(valImg.dataUrl, 'PNG', contentX + 38, y, valImg.wMm, valImg.hMm)
      const lineHeight = Math.max(8, (valImg?.hMm || 8) + 2)
      y += lineHeight
    }
    const totalHeight = y - startY
    doc.roundedRect(contentX, startY - 4, contentWidth, totalHeight + 8, 2, 2)
  }
  const drawFooter = () => {
    const pageWidth = doc.internal.pageSize.getWidth()
    const footerText = getGeneratedAtText()
    doc.setFont('helvetica', 'bold')
    doc.setTextColor(37, 99, 235)
    doc.setFontSize(10)
    doc.text(footerText, pageWidth / 2, 138, { align: 'center' })
  }
  await ensureBengaliFont()
  await drawHeader()
  await drawBody()
  drawFooter()
  const id = transaction?.transactionId || transaction?.id || 'receipt'
  doc.save(`receipt_${id}.pdf`)
  console.log('pdfReceipt: download done')
}